[package]
name = "stlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.4.0"
indexmap = "2.1.0"
pest = "2.7.6"
pest_derive = "2.7.6"
